on: push
jobs:
  build-container:
    name: Building container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3
    - name: Loging to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNMAE }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push to Dcoker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: OurRepo/webapp:latest
